apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: auto-sync-apps
  namespace: argocd  # Changed from 'default' to 'argocd'
spec:
  generators:
    - git:
        repoURL: https://github.com/MidoriAppleCore/argoTestPub.git
        revision: main
        directories:
          - path: argocd/  # Ensure this points to the correct directory containing your app manifests
  template:
    metadata:
      name: '{{path.basename}}-auto-app'  # Makes the application name unique and descriptive
    spec:
      project: default
      source:
        repoURL: https://github.com/MidoriAppleCore/argoTestPub.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd  # All applications will be deployed in the 'argocd' namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
