apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: auto-sync-apps
  namespace: default
spec:
  generators:
    - git:
        repoURL: https://github.com/MidoriAppleCore/argoTestPub.git
        revision: main
        directories:
          - path: argocd/  # This points to the directory in the Git repo containing your app manifests
  template:
    metadata:
      name: '{{path.basename}}-auto-app'  # Makes the application name unique and descriptive
    spec:
      project: default
      source:
        repoURL: https://github.com/MidoriAppleCore/argoTestPub.git
        targetRevision: main
        path: '{{path}}'  # Dynamically sets the path to the application manifest in the specified folder
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'  # Ensure namespaces are properly created or adjust to a fixed namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
