---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/MidoriAppleCore/argoTestPub.git'
    targetRevision: main
    path: 'nginx/'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
