apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/nginx-config' # Replace with your Git repo URL
    targetRevision: HEAD
    path: . # Path to the directory where nginx-deployment.yaml is located
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default # Namespace where you want to deploy Nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
