apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-test
  namespace: argocd  # Namespace aligned with Argo CD installation
spec:
  project: default
  source:
    repoURL: 'https://github.com/MidoriAppleCore/argoTestPub.git'
    targetRevision: main
    path: 'nginx/'  # Path points to the directory containing nginx manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default  # Specifies where to deploy the app resources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
