# PersistentVolumeClaims for MediaWiki and MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-data-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-mediawiki-data-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# MySQL Deployment for MediaWiki
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-mediawiki
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-mediawiki
  template:
    metadata:
      labels:
        app: mysql-mediawiki
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mediawiki_root_password" # Set a secure password
            - name: MYSQL_DATABASE
              value: "mediawiki"
            - name: MYSQL_USER
              value: "mediawiki_user"
            - name: MYSQL_PASSWORD
              value: "mediawiki_password" # Set a secure password
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: mysql-mediawiki-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-mediawiki-data
          persistentVolumeClaim:
            claimName: mysql-mediawiki-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-mediawiki
  namespace: argocd
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql-mediawiki
  type: ClusterIP
---
# MediaWiki Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: mediawiki:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: MW_DB_TYPE
              value: "mysql"
            - name: MW_DB_HOST
              value: "mysql-mediawiki:3306"
            - name: MW_DB_NAME
              value: "mediawiki"
            - name: MW_DB_USER
              value: "mediawiki_user"
            - name: MW_DB_PASSWORD
              value: "mediawiki_password" # Match with MySQL configuration
            - name: MW_SITE_SERVER
              value: "http://mediawiki"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: mediawiki-data
              mountPath: /var/www/html/images
      volumes:
        - name: mediawiki-data
          persistentVolumeClaim:
            claimName: mediawiki-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  namespace: argocd
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app: mediawiki
  type: NodePort
