apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: auto-sync-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MidoriAppleCore/argoTestPub.git
        revision: main
        directories:
          - path: argocd/  # Ensure this directory contains your Application manifests
  template:
    metadata:
      name: '{{path.basename}}-auto-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/MidoriAppleCore/argoTestPub.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
