apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment  
  labels:
    app: nginx-app-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app-test
  template:
    metadata:
      labels:
        app: nginx-app-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: web-content
      volumes:
      - name: web-content
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginx-app-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
