apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-sync-pv
spec:
  capacity:
    storage: 1Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany  # Allows multiple pods to read and write
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/git-sync  # Change to an appropriate path on the host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-sync-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Match with PV size
