apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment  
  labels:
    app: redis-app
spec:
  replicas: 5 # Deploying 5 replicas
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis
        image: redis:latest # Using Redis as the application image
        imagePullPolicy: Always # Ensures the image is always pulled
        ports:
        - containerPort: 6379 # Redis default port
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis-app
  ports:
  - protocol: TCP
    port: 6379 # Redis default port
    targetPort: 6379
