---
apiVersion: v1
kind: Namespace
metadata:
  name: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync-sidecar
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      securityContext:
        fsGroup: 33 # Group ID for www-data (Nginx user)
      containers:
      - name: git-sync
        image: registry.k8s.io/git-sync/git-sync:v3.6.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/MidoriAppleCore/pubsitetest.git"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_ROOT
          value: "/tmp/git-sync" # Temporary directory for git-sync
        - name: GIT_SYNC_DEST
          value: "repo" # Sync to a subdirectory called "repo"
        - name: GIT_SYNC_WAIT
          value: "30"
        volumeMounts:
        - mountPath: /tmp/git-sync
          name: git-sync-volume
      - name: content-mover
        image: busybox
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            if [ -d "/tmp/git-sync/repo" ] && [ "$(ls -A /tmp/git-sync/repo)" ]; then
              rm -rf /usr/share/nginx/html/*
              cp -R /tmp/git-sync/repo/* /usr/share/nginx/html/
              echo "Content copied to Nginx directory"
              sleep 60
            else
              echo "Waiting for git-sync to complete..."
              sleep 5
            fi
          done
        volumeMounts:
        - mountPath: /tmp/git-sync
          name: git-sync-volume
        - mountPath: /usr/share/nginx/html
          name: web-content
      volumes:
      - name: git-sync-volume
        emptyDir: {}
      - name: web-content
        persistentVolumeClaim:
          claimName: git-sync-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: website
  labels:
    app: nginx-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app-test
  template:
    metadata:
      labels:
        app: nginx-app-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: web-content
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: git-sync-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: website
spec:
  type: ClusterIP
  selector:
    app: nginx-app-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-sync-pv
spec:
  capacity:
    storage: 1Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany  # Allows multiple pods to read and write
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/git-sync  # Change to an appropriate path on the host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-sync-pvc
  namespace: website
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Match with PV size
